AWSTemplateFormatVersion: "2010-09-09"
Description: Sample CfnVPC0601
Resources:

#--------------------VPCの設定--------------------
  CfnVPC01:                           #CloudFormation →略語 Cfn
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16  
      Tags:
      - Key: Name
        Value: CfnVPC01

#--------------------サブネットを定義--------------------
# パブリックサブネット_1の設定
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId:
        Ref: CfnVPC01
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet_1

# パブリックサブネット_2の設定
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 1
          - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId:
        Ref: CfnVPC01
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet_2

# プライベートサブネット_1の設定
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId:
        Ref:  CfnVPC01
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet_1

# プライベートサブネット_2の設定
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 1
          - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId:
        Ref:  CfnVPC01
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet_2

#--------------------インターネットGWの設定--------------------
# インターネットGWの設定
  CfnVPC01IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: CfnVPC01_IGW

# インターネットGWをVPC01にアタッチ
  CfnVPV01IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: CfnVPC01
      InternetGatewayId:
        Ref: CfnVPC01IGW

#--------------------ルートテーブルの設定--------------------
#ルートテーブルを定義
  PubSubRoute:
    Type: AWS::EC2::RouteTable
    Properties :
      VpcId:
        Ref: CfnVPC01
      Tags: 
        - Key: Name
          Value: RouteTablePublicFromCF

#ルートをVPC01IGW向けに設定
  PubSubToIGW:
    Type: AWS::EC2::Route
    Properties: 
      RouteTableId:
        Ref: PubSubRoute
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: CfnVPC01IGW

#ルートテーブルとパブリックサブネット_1を関連付け
  PubSub1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PubSubRoute
      SubnetId:
        Ref: PublicSubnet1

#ルートテーブルとパブリックサブネット_2を関連付け
  PubSub2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PubSubRoute
      SubnetId:
        Ref: PublicSubnet2
