AWSTemplateFormatVersion: "2010-09-09"
Description: Sample VPC0301
Resources:

#------------------VOC------------------
  VPC01:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16  
      Tags:
      - Key: Name
        Value: VPC01

#------------------Subnet------------------
# PublicSubnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId:
        Ref: VPC01
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet

# PrivateSubnet
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId:
        Ref:  VPC01
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet