AWSTemplateFormatVersion: "2010-09-09"
Description: Sample VPC01
Resources:
  VPC01:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: VPC02
  subnetName:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'ap-northeast-1a'
      VpcId: !Ref myVPC1
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: Public-1