AWSTemplateFormatVersion: "2010-09-09"
Description: Sample CfnVPC01
Resources:

#--------------------VPC Configuration--------------------
  CfnVPC01:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16  
      Tags:
      - Key: Name
        Value: CfnVPC01

#--------------------Subnet Configuration--------------------
#PublicSubnet_1 Configuration
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId:
        Ref: CfnVPC01
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet_1

#PublicSubnet_2 Configuration
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 1
          - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId:
        Ref: CfnVPC01
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet_2

#PrivateSubnet_1 Configuration
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId:
        Ref:  CfnVPC01
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet_1

#PrivateSubnet_2 Configuration
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 1
          - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId:
        Ref:  CfnVPC01
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet_2

#--------------------Internet Gateway Configuration--------------------
#Internet Gateway Configuration
  CfnVPC01IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: CfnVPC01_IGW

#Internet Gateway Attachment Configuration
  CfnVPV01IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: CfnVPC01
      InternetGatewayId:
        Ref: CfnVPC01IGW

#--------------------RouteTable Configuration--------------------
#RouteTable Configuration
  PubSubRoute:
    Type: AWS::EC2::RouteTable
    Properties :
      VpcId:
        Ref: CfnVPC01
      Tags: 
        - Key: Name
          Value: RouteTablePublicFromCF

#Route to CfnVPC01IGW Configuration
  PubSubToIGW:
    Type: AWS::EC2::Route
    Properties: 
      RouteTableId:
        Ref: PubSubRoute
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: CfnVPC01IGW

#PubSub1RouteTableAssociation Configuration
  PubSub1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PubSubRoute
      SubnetId:
        Ref: PublicSubnet1

#PubSub2RouteTableAssociation Configuration
  PubSub2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PubSubRoute
      SubnetId:
        Ref: PublicSubnet2

Outputs:
#--------------------Output Infomation--------------------
#CfnVPC01 Logical ID
  CfnVPC01:
    Description: VPC ID
    Value:
      Ref: CfnVPC01
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-VPCID"

#PublicSubnet1 Logical ID
  PublicSubnet1:
    Description: PublicSubnet1 ID
    Value:
      Ref: PublicSubnet1
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PrivateSubnet1"

#PrivateSubnet1 Logical ID
  PrivateSubnet1:
    Description: PrivateSubnet1 ID
    Value:
      Ref: PrivateSubnet1
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PublicSubnet1"

#PublicSubnet2 Logical ID
  PublicSubnet2:
    Description: PublicSubnet2 ID
    Value:
      Ref: PublicSubnet2
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PrivateSubnet2"

#PrivateSubnet2 Logical ID
  PrivateSubnet2:
    Description: PrivateSubnet2 ID
    Value:
      Ref: PrivateSubnet2
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PublicSubnet2"
