AWSTemplateFormatVersion: "2010-09-09"
Description: Sample VPC0502
Resources:

#--------------------VPCの設定--------------------
  VPC01:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16  
      Tags:
      - Key: Name
        Value: VPC01

#--------------------サブネットを定義--------------------
# パブリックサブネットの設定
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId:
        Ref: VPC01
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet

# プライベートサブネットの設定
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId:
        Ref:  VPC01
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet          

#--------------------インターネットGWの設定--------------------
# インターネットGWの設定
  VPC01IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: VPC01_IGW

# インターネットGWをVPC01にアタッチ
  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC01
      InternetGatewayId:
        Ref: VPC01IGW

#--------------------ルートテーブルの設定--------------------
# ルートテーブルを定義
  PubSubRoute:
    Type: AWS::EC2::RouteTable
    Properties :
      VpcId:
        Ref: VPC01
      Tags: 
        - Key: Name
          Value: PubSubRouteTable

#ルートテーブルとパブリックサブネットを関連付け
  PubSubRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PubSubRoute
      SubnetId:
        Ref: PublicSubnet